query ($id: Int!) {
  story(id: $id) {
    id
    title
    text
    url
    score
    user_id
    comments {
      id
      text
      posted_at
      user_id
      score
      descendants
      parent_comment_id
    }
  }
}
