query ($id: Int!) {
  story(id: $id) {
    id
    title
    text
    url
    score
    user_id
    comments(where: {dead: {_eq: false}, deleted: {_eq: false}, user_id: {_is_null: false}}) {
      id
      text
      posted_at
      user_id
      score
      parent_comment_id
    }
    webpage {
      article {
        id
        expected_reading_time
      }
    }
  }
}
