query ($id: Int!){
  story(id: $id) {
    id
    descendants
    webpage {
      article {
        id
        author
        headline
        published_at
        html
        main_image
        canonical_url
      }
    }
  }
}
