query ($startDate: timestamptz!, $endDate: timestamptz!) {
  stories(where: {score: {_gte: 1}, posted_at: {_gte: $startDate, _lte: $endDate}}, order_by: {score: desc}, limit: 30) {
    id
    title
    text
    url
    score
    descendants
    user_id
  }
}
