query ($startDate: timestamptz!, $endDate: timestamptz!) {
  stories(where: {dead: {_eq: false}, score: {_gte: 10}, posted_at: {_gte: $startDate, _lte: $endDate}}, order_by: {score: desc}) {
    id
    title
    url
    score
    descendants
    webpage {
      article {
        id
      }
    }
    user {
      id
    }
  }
}
