[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  NODE_ENV = "Environment ('development' or 'production')"
  FRONTEND_URL = "Frontend URL"
  BACKEND_URL = "Backend URL"
  SIMPLE_ANALYTICS_URL = "Simple Analytics URL"
