query ($id: Int!) {
  story(id: $id) {
    id
    title
    text
    url
    score
    user {
      id
    }
    comments(where: {dead: {_eq: false}, deleted: {_eq: false}}) {
      id
      text
      deleted
      posted_at
      parent_comment_id
      user {
        id
      }
    }
    webpage {
      article {
        id
        expected_reading_time
      }
    }
  }
}
